# Generated by Django 5.1.6 on 2025-02-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('price_type', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('high', 'High'), ('low', 'Low')], max_length=10)),
                ('operator', models.CharField(choices=[('>=', '≥'), ('<=', '≤')], max_length=2)),
                ('threshold', models.FloatField()),
                ('alert_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
