# Generated by Django 5.1.6 on 2025-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=3),
        ),
        migrations.AddField(
            model_name='alert',
            name='trend',
            field=models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish')], default='Bullish', max_length=10),
        ),
    ]
